Redis:
  address: 127.0.0.1
  port: 6379
MongoDB:
  address: 127.0.0.1
  port: 27017
# configure isto da forma que está configurado a sua pasta de configurações do seu servidor
# lembre-se de ativar o modo bungee-cord, também, o bungeecord já deve está iniciado.
# REDECRYSTAL
# cuidado com o motd
Server-info:
  motd: 'Lobby'
  address: 127.0.0.1
  port: 25566
  name: 'Lobby-1'
  priority: true